version: '3.5'

services:
  template-workspace-remote-ssh:
    image: geircode/template-workspace-remote-ssh:latest
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: template-workspace-remote-ssh-1
    volumes:
      - ".:/app"       
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - template-workspace-remote-ssh_network
networks:
  template-workspace-remote-ssh_network:
          