version: '3.7'

services:
  template_workspace_remote_ssh:
    image: geircode/template_workspace_remote_ssh:latest
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: template_workspace_remote_ssh-1
    volumes:
      # - ".:/app"       
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - template_workspace_remote_ssh_network
networks:
  template_workspace_remote_ssh_network:
          