version: '3.7'

services:
  template_workspace_remote_ssh-filecontainer:
    image: geircode/template_workspace_remote_ssh-filecontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template_workspace_remote_ssh-filecontainer-1
    networks:
      - template_workspace_remote_ssh-filecontainer-network      

networks:
  template_workspace_remote_ssh-filecontainer-network:
    name: template_workspace_remote_ssh-filecontainer-network    
    