version: '3.5'

services:
  template-workspace-remote-ssh_secrets:
    image: geircode/template-workspace-remote-ssh_secrets:latest
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: dockersecrets__template-workspace-remote-ssh-1
    volumes:
      - "../../DockerSecrets/template-workspace-remote-ssh_secrets:/template-workspace-remote-ssh_secrets"
    working_dir: /template-workspace-remote-ssh_secrets
    networks:
      - template-workspace-remote-ssh_secrets-network    
networks:
  template-workspace-remote-ssh_secrets-network:

