version: '3.5'

services:
  template_workspace_remote_ssh_secrets:
    image: geircode/template_workspace_remote_ssh_secrets:latest
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: dockersecrets__template_workspace_remote_ssh-1
    volumes:
      - "../../DockerSecrets/template_workspace_remote_ssh_secrets:/template_workspace_remote_ssh_secrets"
    working_dir: /template_workspace_remote_ssh_secrets
    networks:
      - template_workspace_remote_ssh_secrets-network    
networks:
  template_workspace_remote_ssh_secrets-network:

