version: '3.5'

services:
  template_workspace_remote_ssh-builder:
    image: geircode/template_workspace_remote_ssh-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template_workspace_remote_ssh-builder-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../.:/app"
      # - ".:/app-scripts"             
    secrets:
      - source: dockerloginpassword      
    networks:
      - template_workspace_remote_ssh-builder-network      
secrets:
  dockerloginpassword:
    file: ../../DockerSecrets/template_workspace_remote_ssh_secrets/dockerloginpassword

networks:
  template_workspace_remote_ssh-builder-network:
    name: template_workspace_remote_ssh-builder-network    
    