version: '3.7'

services:
  template_workspace_remote_ssh-runner:
    image: geircode/template_workspace_remote_ssh-runner:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template_workspace_remote_ssh-runner-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../.:/app"        
    secrets:
      - source: dockerloginpassword      
    networks:
      - template_workspace_remote_ssh-runner-network      
secrets:
  dockerloginpassword:
    file: ../../DockerSecrets/template_workspace_remote_ssh_secrets/dockerloginpassword

networks:
  template_workspace_remote_ssh-runner-network:
    name: template_workspace_remote_ssh-runner-network    
    