version: '3.5'

services:
  template-workspace-remote-ssh-runner:
    image: geircode/template-workspace-remote-ssh-runner:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-workspace-remote-ssh-runner-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../.:/app"        
    secrets:
      - source: dockerloginpassword      
    networks:
      - template-workspace-remote-ssh-runner-network      
secrets:
  dockerloginpassword:
    file: ../../DockerSecrets/template-workspace-remote-ssh_secrets/dockerloginpassword

networks:
  template-workspace-remote-ssh-runner-network:
    name: template-workspace-remote-ssh-runner-network    
    